# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: 'assets/uploads'
collections:
  - name: 'notebook'
    label: 'Notebook'
    folder: 'notebook/_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Category', name: 'category', widget: 'hidden', default: 'notebook' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Text', name: 'text', widget: 'markdown' }
  - name: 'camera-roll'
    label: 'Camera Roll'
    folder: 'camera-roll/_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Category', name: 'category', widget: 'hidden', default: 'camera-roll' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: "Images"
        name: "images"
        widget: "list"
        fields: 
          - {label: File, name: file, widget: image}
          - {label: Caption, name: caption, widget: text}